### ISSUE TITLE
Avoid entering excluded directories

### ISSUE THREAD

**Issue by skeggse** [hashicorp/go-slug#19]
Let's say we're in a large monorepo, and we'd like to exclude all the `node_modules/` directories (they might not be checked in, even). It'd be nice if I could put `node_modules/` in the `.terraformignore` file and have it not even traverse that directory - it seems that's how it currently works, because the total runtime for `Pack` seems to remain the same even with that directive.

**Comment by skeggse** [comment]
Hey @brandonc - any interest in moving this along? It'd help a lot for organizations that stick their terraform in a mixed-use monorepo.

**Comment by brandonc** [comment]
@skeggse I'll be glad to evaluate this. I need a few more days, though! Thanks for calling it out, it's helpful to know this is still relevant to you

**Comment by skeggse** [comment]
Sounds good, thanks! I forgot to link to the pull request - https://github.com/hashicorp/go-slug/pull/21 implements the improvements I'm looking for :)

**Comment by felipeplets** [comment]
This is a performance problem in our monorepo. Thank you for raising it and proposing a PR @skeggse.

**Comment by brandonc** [comment]
@felipeplets @skeggse This is now available as of terraform [v1.7.0-rc1](https://github.com/hashicorp/terraform/releases/tag/v1.7.0-rc1). [The docs](https://developer.hashicorp.com/terraform/cli/v1.7.x/cloud/settings#excluding-files-from-upload-with-terraformignore) were modified slightly with new guidance. Would love to know if this solved your performance problem.
