### ISSUE TITLE
`Pack` fails to handle multiple levels of symlinks

### ISSUE THREAD

**Issue by jbardin** [hashicorp/go-slug#32]
The `packWalkFn` assumes a symlink always points to a regular file. If we encounter a symlink which needs to be dereferenced, the target info is read via `Lstat`, but the archive header is always set to be a regular file and the metadata for the symlink will not match what is copied with `writeBody = true` (https://github.com/hashicorp/go-slug/blob/master/slug.go#L254) further down.

See https://github.com/hashicorp/terraform/issues/31895

**Comment by alexlokshin-czi** [comment]
We're seeing the same exact issue. Ever since v0.10.0 was released, symlinks are broken. For now, pinning `go-slug` to `v0.9.1` fixes the problem.
